version: '3.9'

services:       
  appvamserlike:
    restart: always    
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # 컨테이너 내부는 그대로 5202를 사용해도 됨
      - ASPNETCORE_URLS=http://+:5202
    ports:
      # [호스트포트]:[컨테이너포트]
      # 80번으로 들어오면 컨테이너의 5202번으로 전달해!
      - "80:5202"
    networks:
      - appnetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-northeast-2"
        awslogs-group: "/ec2/vamserlike-backend" # 원하는 로그 그룹 이름
        awslogs-create-group: "true" # 그룹이 없으면 자동으로 생성해줌
        awslogs-stream: "backend-log-stream"
      
networks:
  appnetwork:
    driver: bridge