version: '3.9'

services:       
  appvamserlike:
    restart: always    
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # 컨테이너 내부는 그대로 5202를 사용해도 됨
      - ASPNETCORE_URLS=http://+:5202
    ports:
      # [호스트포트]:[컨테이너포트]
      # 80번으로 들어오면 컨테이너의 5202번으로 전달해!
      - "80:5202"
    networks:
      - appnetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
networks:
  appnetwork:
    driver: bridge